name: FireWorksDX
version: @version@-@apiversion@
description: FireWorksDX
author: DartPower
website: https://github.com/dptmc/FireWorksDX
main: io.dpteam.FireWorksDX.Main
commands:
   fw:
      description: Запуск фейрверка.